USE bd_rede_entregas

DROP PROCEDURE IF EXISTS SP_DIM_MODALIDADE

CREATE OR ALTER PROCEDURE SP_DIM_MODALIDADE (@DATA_CARGA DATETIME) AS
BEGIN
	DECLARE @COD_MODALIDADE INT, @MODALIDADE VARCHAR(45), @COD_TRANSPORTADORA INT

	DECLARE C_MODALIDADE CURSOR FOR 
	SELECT cod_modalidade, modalidade, cod_transportadora FROM Aux_Modalidade
	WHERE DATA_CARGA = @DATA_CARGA

	OPEN C_MODALIDADE
	FETCH C_MODALIDADE INTO @COD_MODALIDADE, @MODALIDADE, @COD_TRANSPORTADORA

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		-- UPDATE
		IF EXISTS (SELECT cod_modalidade FROM Dim_Modalidade WHERE cod_modalidade = @COD_MODALIDADE)
		BEGIN
			UPDATE Dim_Modalidade SET modalidade = @MODALIDADE, cod_transportadora = @COD_TRANSPORTADORA
			WHERE cod_modalidade = @COD_MODALIDADE
		END
		-- INSERT
		ELSE
		BEGIN
			INSERT INTO Dim_Modalidade(cod_modalidade, modalidade, cod_transportadora)
									  VALUES(@COD_MODALIDADE, @MODALIDADE, @COD_TRANSPORTADORA)
		END

		FETCH C_MODALIDADE INTO @COD_MODALIDADE, @MODALIDADE, @COD_TRANSPORTADORA
	END
	CLOSE C_MODALIDADE
	DEALLOCATE C_MODALIDADE
END