USE bd_rede_entregas

CREATE OR ALTER PROCEDURE SP_DIM_TRANSPORTADORA (@DATA_CARGA DATETIME) AS
BEGIN
	DECLARE @COD_TRANSPORTADORA INT, @TRANSPORTADORA VARCHAR(45), @CNPJ VARCHAR(20)

	DECLARE C_TRANSPORTADORA CURSOR FOR 
	SELECT cod_transportadora, transportadora, CNPJ FROM Aux_Transportadora
	WHERE DATA_CARGA = @DATA_CARGA

	OPEN C_TRANSPORTADORA
	FETCH C_TRANSPORTADORA INTO @COD_TRANSPORTADORA, @TRANSPORTADORA, @CNPJ

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		-- UPDATE
		IF EXISTS (SELECT cod_transportadora FROM Dim_Transportadora WHERE cod_transportadora = @COD_TRANSPORTADORA)
		BEGIN
			UPDATE Dim_Transportadora SET transportadora = @TRANSPORTADORA, CNPJ = @CNPJ
			WHERE cod_transportadora = @COD_TRANSPORTADORA
		END
		-- INSERT
		ELSE
		BEGIN
			INSERT INTO Dim_Transportadora(cod_transportadora, transportadora, CNPJ)
									  VALUES(@COD_TRANSPORTADORA, @TRANSPORTADORA, @CNPJ)
		END

		FETCH C_TRANSPORTADORA INTO @COD_TRANSPORTADORA, @TRANSPORTADORA, @CNPJ
	END
	CLOSE C_TRANSPORTADORA
	DEALLOCATE C_TRANSPORTADORA
END