USE bd_rede_entregas

CREATE OR ALTER PROCEDURE SP_DIM_LOCALIDADE (@DATA_CARGA DATETIME) AS
BEGIN
	DECLARE @COD_REGIAO INT, @REGIAO CHAR(12), @COD_ESTADO INT,
			@ESTADO VARCHAR(45), @UF CHAR(2), @COD_CIDADE INT,
			@CIDADE VARCHAR(50), @COD_BAIRRO INT, @BAIRRO VARCHAR(100)

	DECLARE C_LOCALIDADE CURSOR FOR 
	SELECT COD_REGIAO, REGIAO, COD_ESTADO,
		   ESTADO, UF, COD_CIDADE, CIDADE,
		   COD_BAIRRO, BAIRRO FROM AUX_LOCALIDADE
	WHERE DATA_CARGA = @DATA_CARGA

	OPEN C_LOCALIDADE
	FETCH C_LOCALIDADE INTO @COD_REGIAO, @REGIAO, @COD_ESTADO,
			@ESTADO, @UF, @COD_CIDADE,
			@CIDADE, @COD_BAIRRO, @BAIRRO

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		-- UPDATE
		IF EXISTS (SELECT COD_BAIRRO FROM Dim_Localidade WHERE cod_bairro = @COD_BAIRRO)
		BEGIN
			UPDATE Dim_Localidade SET cod_regiao = @COD_REGIAO, regiao = @REGIAO, cod_estado = @COD_ESTADO,
			estado = @ESTADO, UF = @UF, cod_cidade = @COD_CIDADE, cidade = @CIDADE, cod_bairro = @COD_BAIRRO,
			bairro = @BAIRRO
		END
		-- INSERT
		ELSE
		BEGIN
			INSERT INTO Dim_Localidade(cod_regiao, regiao, cod_estado, estado, UF, cod_cidade,
									   cidade, cod_bairro, bairro)
									  VALUES(@COD_REGIAO, @REGIAO, @COD_ESTADO, @ESTADO,
											 @UF, @COD_CIDADE, @CIDADE, @COD_BAIRRO, @BAIRRO)
		END

		FETCH C_LOCALIDADE INTO @COD_REGIAO, @REGIAO, @COD_ESTADO,
			@ESTADO, @UF, @COD_CIDADE,
			@CIDADE, @COD_BAIRRO, @BAIRRO
	END
	CLOSE C_LOCALIDADE
	DEALLOCATE C_LOCALIDADE
END