USE bd_rede_entregas

DROP PROCEDURE IF EXISTS SP_OLTP_TRANSPORTADORA

CREATE OR ALTER PROCEDURE SP_OLTP_TRANSPORTADORA (@DATA_CARGA DATETIME) AS
BEGIN
	DELETE Aux_Transportadora WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO Aux_Transportadora
	SELECT @DATA_CARGA, T.id, T.transportadora, T.CNPJ FROM Transportadora T
END