USE bd_rede_entregas

CREATE OR ALTER PROCEDURE SP_OLTP_STATUS (@DATA_CARGA DATETIME) AS
BEGIN
	DELETE Aux_Status WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO Aux_Status
	SELECT @DATA_CARGA, S.id, S.status FROM Status S
END