USE bd_rede_entregas

DROP PROCEDURE IF EXISTS SP_OLTP_REALIZAR_CARGA

CREATE OR ALTER PROCEDURE SP_OLTP_REALIZAR_CARGA (@DATA_CARGA DATETIME, 
												  @DATA_INICIAL DATETIME, 
												  @DATA_FINAL DATETIME) AS
BEGIN
	EXEC SP_OLTP_ENTREGA @DATA_CARGA, @DATA_INICIAL, @DATA_FINAL
	EXEC SP_OLTP_LOCALIDADE @DATA_CARGA
	EXEC SP_OLTP_MODALIDADE @DATA_CARGA
	EXEC SP_OLTP_STATUS @DATA_CARGA
	EXEC SP_OLTP_TRANSPORTADORA @DATA_CARGA
END

-- Trocar os ultimos parametros por datas que sejam compativeis com o atributo
-- dataAtualizacao na tabela de Entrega
EXEC SP_OLTP_REALIZAR_CARGA '20221118', '20221118', '20221118'
SELECT * FROM Aux_Entrega
SELECT * FROM Aux_Localidade
SELECT * FROM Aux_Modalidade
SELECT * FROM Aux_Status
SELECT * FROM Aux_Transportadora