USE bd_rede_entregas

INSERT INTO Estado(estado, UF, idRegiao)VALUES('Rondônia','RO',1)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Acre','AC',1)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Amazonas','AM',1)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Roraima','RR',1)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Pará','PA',1)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Amapá','AP',1)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Tocantins','TO',1)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Maranhão','MA',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Piauí','PI',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Ceará','CE',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Rio Grande do Norte','RN',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Paraíba','PB',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Pernambuco','PE',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Alagoas','AL',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Sergipe','SE',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Bahia','BA',2)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Minas Gerais','MG',3)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Espírito Santo','ES',3)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Rio de Janeiro','RJ',3)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('São Paulo','SP',3)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Paraná','PR',4)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Santa Catarina','SC',4)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Rio Grande do Sul','RS',4)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Mato Grosso do Sul','MS',5)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Mato Grosso','MT',5)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Goiás','GO',5)
INSERT INTO Estado(estado, UF, idRegiao)VALUES('Distrito Federal','DF',5)
