INSERT INTO Regiao(regiao)VALUES('Sul')
INSERT INTO Regiao(regiao)VALUES('Nordeste')
INSERT INTO Regiao(regiao)VALUES('Norte')
INSERT INTO Regiao(regiao)VALUES('Centro-Oeste')
INSERT INTO Regiao(regiao)VALUES('Sudeste')
